In [43]:
import mysql.connector as dbcon
#db=dbcon.connect(host="localhost",user="root",password="root",database="employeeinfo")
#db_cor=db.cursor()

In [57]:
class EmployeeDatabase(object):
    db=dbcon.connect(host="localhost",user="root",password="root",database="employeeinfo")
    db_cor=db.cursor()
    Empid=None
    First_name=None
    Last_name=None
    Age=None
    Gender=None
    Salary=None
    City=None
    Department=None
    def __init__(self,Empid,First_name,Last_name,Age,Gender,Salary,City,Department):
        self.Empid=Empid
        self.First_name=First_name
        self.Last_name=Last_name
        self.Age=Age
        self.Gender=Gender
        self.Salary=Salary
        self.City=City
        self.Department=Department
        
    def Insert(self):
        statement=f'''insert into Employee values({self.Empid},'{self.First_name}','{self.Last_name}'
        ,{self.Age},'{self.Gender}',{self.Salary},'{self.City}','{self.Department}')'''
        db_cor.execute(statement)
        db.commit()
        
    #def Update(self,col_val):
    
    def selectQuery(self):
        state="Select * from Employee"
        db_cor=self.db.cursor()
        db_cor.execute(state)
        rows=db_cor.fetchall()
        self.db.close()
        for row in rows:
            print(row)
    
    
    def Update(self,Gender,First_name):
        state=f"update Employee Set Gender='{self.Gender}' where First_name='{self.First_name}'"
        db_cor=self.db.cursor()
        db_cor.execute(state)
        db.commit()
        rows=db_cor.fetchall()
        db.close()
        print("After Update........................!.")
        for row in rows:
            print(row)
            
            
    def Delete(self,First_name):
        state=f"Delete from Employee where First_name='{self.First_name}'"
        db_cor=self.db.cursor()
        db_cor.execute(state)
        db.commit()
        rows=db_cor.fetchall()
        db.close()
        print("After Delete........................!.")
        for row in rows:
            print(row)
    
    
db=EmployeeDatabase(4,'tomy','philips',24,'Female',40000,'Pune','HR')
#db1.Insert()
db.selectQuery()
#db1.Update("Female","john")
#db1.Delete('john')

(1, 'Sakharam', 'Rajegore', 23, 'Male', 30000, 'Pune', 'IT')
(2, 'john', 'Devid', 24, 'Male', 45000, 'Banglore', 'IT')
(3, 'tomy', 'philips', 24, 'Female', 40000, 'Pune', 'HR')
(4, 'tomy', 'philips', 24, 'Female', 40000, 'Pune', 'HR')

In [50]:
class Department(object):
    import mysql.connector as dbcon
    db1=dbcon.connect(host="localhost",user="root",password="root",database="employeeinfo")
    db_cor1=db1.cursor()

    DeptId=None
    Deptname=None
   
    def __init__(self,DeptId,Deptname):
        self.DeptId=DeptId
        self.Deptname=Deptname
        
        
    def Insert(self):
        
        db_cor1=self.db1.cursor()
        statement=f'''insert into Department values({self.DeptId},'{self.Deptname}')'''
        db_cor1.execute(statement)
        db1.commit()
        
    #def Update(self,col_val):
    
    def selectQuery(self):
        state="Select * from Department"
        db_cor1=self.db1.cursor()
        db_cor1.execute(state)
        rows=db_cor1.fetchall()
        db1.close()
        for row in rows:
            print(row)
    
    
    def Update(self,Deptname,DeptId):
        state=f"update Department Set Deptname='{self.Deptname}' where DeptId='{self.DeptId}'"
        db_cor=self.db1.cursor()
        db_cor.execute(state)
        db.commit()
        rows=db_cor.fetchall()
        db.close()
        print("After Update........................!.")
        for row in rows:
            print(row)
            
            
    def Delete(self,DeptId):
        state=f"Delete from Department where DeptId='{self.DeptId}'"
        db_cor=self.db1.cursor()
        db_cor.execute(state)
        db.commit()
        rows=db_cor.fetchall()
        db.close()
        print("After Delete........................!.")
        for row in rows:
            print(row)
    
    
db=Department(2,'Netwotk')

db1=dbcon.connect(host="localhost",user="root",password="root",database="employeeinfo")
db.Insert()
db.selectQuery()
#db1.Update("Female","john")
#db1.Delete('john')

(11, 'IT')
(2, 'Netwotk')

#